name: dry-types
custom_ci: true
codacy_id: f2d71613195f4da993acb9ac9d6ea336
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica@gmail.com"]
  summary: "Type system for Ruby supporting coercions, constraints and complex types like structs, value objects, enums etc"
  runtime_dependencies:
    - [bigdecimal, "~> 3.0"]
    - [concurrent-ruby, "~> 1.0"]
    - [zeitwerk, "~> 2.6"]
    - [dry-core, "~> 1.0"]
    - [dry-inflector, "~> 1.0"]
    - [dry-logic, "~> 1.4"]
